server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                   #开启动态路由功能，通过微服务名进行路由
      routes:
        - id: payment_routh               #路由器ID，要求唯一
          #uri: http://localhost:8001      #匹配后提供服务的地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的地址
          predicates:
            - Path=/payment/get/**           #断言，路径相匹配的进行路由
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的地址
          predicates:
            - Path=/payment/**

eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

