server:
  port: 80

spring:
  application:
    name: cloud-order-openfeign-service

eureka:
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


logging:
  level:
    com.xinle.springcloud.service.PaymentService: debug